const TIMELINE_MIN_HEIGHT=170, TIMELINE_MAX_RATIO=.55, WORKSPACE_CHROME_HEIGHT=330, DEFAULT_TRACK_COUNT=2, TIMELINE_AUTO_BASE_HEIGHT=190, IMPORTED_TRACK_HEIGHT=42, WORKSPACE_DOCKED_MIN_WIDTH=1180;
export interface TimelineBounds { readonly min:number; readonly max:number; readonly defaultHeight:number; }
export function timelineHeightBounds(viewportHeight: unknown): TimelineBounds { let height=Number(viewportHeight); if(!Number.isFinite(height))height=640; height=Math.max(640,Math.round(height)); const max=Math.max(TIMELINE_MIN_HEIGHT,Math.min(Math.round(height*TIMELINE_MAX_RATIO),height-WORKSPACE_CHROME_HEIGHT)); return {min:TIMELINE_MIN_HEIGHT,max,defaultHeight:Math.min(max,TIMELINE_AUTO_BASE_HEIGHT)}; }
export function timelineAutoHeight(trackCount: unknown, viewportHeight: unknown):number { const bounds=timelineHeightBounds(viewportHeight); let count=Math.round(Number(trackCount)); if(!Number.isFinite(count))count=DEFAULT_TRACK_COUNT; count=Math.max(DEFAULT_TRACK_COUNT,count); return Math.min(bounds.max,bounds.defaultHeight+(count-DEFAULT_TRACK_COUNT)*IMPORTED_TRACK_HEIGHT); }
export function clampTimelineHeight(value:unknown, viewportHeight:unknown, trackCount?:unknown):number { const bounds=timelineHeightBounds(viewportHeight); const height=Number(value); return !Number.isFinite(height)||height<=0?timelineAutoHeight(trackCount,viewportHeight):Math.max(bounds.min,Math.min(bounds.max,Math.round(height))); }
export function normalizeTimelineHeightSetting(value:unknown, viewportHeight:unknown):number { const bounds=timelineHeightBounds(viewportHeight),height=Number(value); return !Number.isFinite(height)||height<bounds.min?0:Math.round(height); }
export function initialTimelineHeightSetting(settings: Readonly<Record<string, unknown>> | null | undefined):unknown { return settings?.timeline_height ?? 0; }
export function timelineHeightForTrackCount(setting: unknown, trackCount: unknown, viewportHeight: unknown, previousTrackCount: unknown = trackCount): number | null {
  if (trackCount === previousTrackCount && normalizeTimelineHeightSetting(setting, viewportHeight) !== 0) return null;
  return timelineAutoHeight(trackCount, viewportHeight);
}
export function timelineHeightForKey(current:unknown,key:string,largeStep:boolean,viewportHeight:unknown):number|null{const bounds=timelineHeightBounds(viewportHeight);if(key==="Home")return bounds.min;if(key==="End")return bounds.max;const direction=key==="ArrowUp"?1:key==="ArrowDown"?-1:0;return direction?clampTimelineHeight(Number(current)+direction*(largeStep?32:10),viewportHeight):null;}
export function workspaceMode(viewportWidth:unknown):"docked"|"overlay"{let width=Number(viewportWidth);if(!Number.isFinite(width))width=WORKSPACE_DOCKED_MIN_WIDTH;return width>=WORKSPACE_DOCKED_MIN_WIDTH?"docked":"overlay";}
export function initialWorkspacePanels(viewportWidth:unknown):{libraryOpen:boolean;inspectorOpen:boolean}{const open=workspaceMode(viewportWidth)==="docked";return{libraryOpen:open,inspectorOpen:open};}
export function toggleWorkspacePanelState(state:{libraryOpen?:boolean;inspectorOpen?:boolean}|null|undefined,panel:string,viewportWidth:unknown):{libraryOpen:boolean;inspectorOpen:boolean}{const current={libraryOpen:Boolean(state?.libraryOpen),inspectorOpen:Boolean(state?.inspectorOpen)};if(panel!=="library"&&panel!=="inspector")return current;const key=panel==="library"?"libraryOpen":"inspectorOpen";if(workspaceMode(viewportWidth)==="docked")return{...current,[key]:!current[key]};const opening=!current[key];return{libraryOpen:panel==="library"&&opening,inspectorOpen:panel==="inspector"&&opening};}
